---
webapp:
  TestWHP1:
    webapp_name: TestWHP1
    kind: Windows
    asp: asp-demopondichys-poc
    asprg: rg-demopondichys-poc
    connectionstring:
      name: Database
      type: SQLServer
      value: Server=some-server.mydomain.com;Integrated Security=SSPI
    app_settings:
      testAppSetting1: Abcd.12345
      testAppSetting2: Cloud
      testAppSetting3: Dev